### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by shim94kr** [snap-research/discoscene#1]
Hello. Thank you for sharing this amazing project!

May I know when the code will be released?

I am looking forward to running this project!

**Comment by rockywind** [comment]
+1

**Comment by SongQiPing** [comment]
+1

**Comment by SongQiPing** [comment]
I think your work is very interesting, so when will the code be open source?

**Comment by qiisun** [comment]
+1

**Comment by Pamimi** [comment]
++1

**Comment by justimyhxu** [comment]
Thanks for your interest in my work! Currently, I buried myself with NeurIPS submission. I will try my best to release the code in May or June. Sorry for that. But if you want to reproduce my results and have any questions, feel free to contact me via email.

**Comment by OrangeSodahub** [comment]
Hello, is there any plans to release the code of this excellent work?

**Comment by hanxuel** [comment]
Hello, any plans to release the code of this excellent work?

**Comment by OrangeSodahub** [comment]
@justimyhxu  Hello, is there any plans to release the code of this excellent work?
